import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-full lg:flex-row flex-col">
        <Sidebar />
        <div className="flex-grow lg:ml-72 p-4 min-h-full">
          {children} <ToastContainer />
        </div>
      </body>
    </html>
  );
}
